name: lint, format and compile

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/fe

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'node'
          cache: 'npm'
          cache-dependency-path: apps/fe/package-lock.json


      - name: Install dependencies
        run: npm ci

      - name: Run lint and format
        run: npm run ci

      - name: Run compile
        run: npm run compile
